version: '3'

services:
  kafka-producer:
    image: kafka/docker-kafka-producer:0.0.1-SNAPSHOT
    restart: on-failure
    ports:
      - 8881:8080
  kafka-consumer:
    image: kafka/docker-kafka-producer:0.0.1-SNAPSHOT
    restart: on-failure
    ports:
      - 8082:8080
