version: '3'

services:
  kafka-producer:
    build: 2-spring-kafka-producer/.
    image: kafka/docker-kafka-producer
    restart: on-failure
    ports:
      - 8881:8080
  kafka-consumer:
    build: 2-spring-kafka-consumer/.
    image: kafka/docker-kafka-consumer
    restart: on-failure
    ports:
      - 8882:8080
