version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "my-topic:1:1"
#  kafka-producer:
#    image: kafka/docker-kafka-producer:0.0.1-SNAPSHOT
#    restart: on-failure
#    depends_on:
#      - zookeeper
#      - kafka
#    ports:
#      - 8881:8080
#  kafka-consumer:
#    image: kafka/docker-kafka-producer:0.0.1-SNAPSHOT
#    restart: on-failure
#    depends_on:
#      - zookeeper
#      - kafka
#    ports:
#      - 8082:8080
